version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: challenge_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: challenge_db

  app:
    build: .
    container_name: challenge_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      DATABASE_URL: "mongodb://mongo:27017/challenge_db"
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongo-data:
